# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - meme-app-project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e782be02fd5c43b0b9fc1b52e4f0a6e8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_38f887d5fb1d45f79942dcad74030c83 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e782be02fd5c43b0b9fc1b52e4f0a6e8 }}/meme-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'meme-app-project'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1882f796464f4a17954e328e19065cca }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e782be02fd5c43b0b9fc1b52e4f0a6e8 }}/meme-app:${{ github.sha }}'